# Generated by Django 3.1 on 2020-08-20 00:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.TextField(default='bio')),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('profile_Id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
